plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 20

Metrics/ParameterLists:
  Max: 6

RSpec/NestedGroups:
  Max: 5

Metrics/ClassLength:
  Exclude:
    - 'lib/shopify_theme_builder/liquid_processor.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/shopify_theme_builder/command_line.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/shopify_theme_builder/command_line.rb'
