#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "shopify_theme_builder"

$stdout.sync = true

if ARGV.empty?
  ShopifyThemeBuilder.watch
else
  ShopifyThemeBuilder.watch(folders_to_watch: ARGV)
end
